### ISSUE TITLE
Not showing Skin.

### ISSUE THREAD

**Issue by laGameTV** [MauritsWilke/mcpfp#13]
I tried my username "laGameTV" and it just shows up as Steve. My second account works. Also my skin shows up correctly on Minotar.
![chrome_Phjxe8jYwe](https://user-images.githubusercontent.com/31692271/232091507-84c87a1d-3c2d-4892-bfea-46ffc6619e96.png)

**Comment by MauritsWilke** [comment]
Seems to be a minotaur issue, I checked the link and it returns a steve skin.
Do you have a Java account?

**Comment by laGameTV** [comment]
Yes of course.

**Comment by laGameTV** [comment]
Minotar renders my skin just fine. At least for me.
![image](https://user-images.githubusercontent.com/31692271/232102757-e93efba1-927f-4d76-a487-861b53b63c69.png)
![image](https://user-images.githubusercontent.com/31692271/232102790-e379ca9d-f883-4e3f-9dab-22033f1a9ad6.png)

**Comment by MauritsWilke** [comment]
Sorry for not responding sooner, but it seems to be working fine now?

**Comment by laGameTV** [comment]
yes. i dont know why but it does.
