### ISSUE TITLE
Suggestion: API support?

### ISSUE THREAD

**Issue by qing762** [MauritsWilke/mcpfp#14]
title

**Comment by MauritsWilke** [comment]
There is an API that you can use:
`https://minecraftpfp.com/api/pfp/{{USERNAME}}.png?gradient={{HEX}}-{{HEX}}`

The gradient is from top to bottom and you can add as many colours as you want:
https://minecraftpfp.com/api/pfp/I_Like_Cats__.png?gradient=fdeff9-ec38bc-7303c0-03001e
