### ISSUE TITLE
Only information

### ISSUE THREAD

**Issue by uwuv3** [MauritsWilke/mcpfp#17]
I made a bot called "Minecraft PFP Generator" on Discord without your permission and added features such as adding skins, custom gradients, etc. At first I thought no one would use it, but a lot of people liked it.(I apologize I shouldn't ask this now) Do you have permission?

**Comment by MauritsWilke** [comment]
Yea all the code falls under the [MIT](https://github.com/MauritsWilke/mcpfp/blob/main/licence.md) licence! So do whatever you want with it :)
