### ISSUE TITLE
The downloaded profile picture .png from the site displays incorrectly

### ISSUE THREAD

**Issue by ghost** [MauritsWilke/mcpfp#2]
![mcpfp - DuplexEagle](https://user-images.githubusercontent.com/103918667/179388737-195da0bc-3296-4f91-9ab8-6f98a2ff1963.png)
This is the image that I downloaded from the site. I'm using a Firefox based browser on Linux but there's no reason this should make a difference.

If you want to try it yourself my Minecraft username is DuplexEagle.

**Comment by MauritsWilke** [comment]
Hey thanks for reporting the bug! I'll see if it's a quick fix or not, because V2 is currently in development and I won't spend too much time on fixing V1.

**Comment by ghost** [comment]
No worries. I was looking for a way to get a profile picture for my skin and found your website, but it didn't work and I just thought it would be worth reporting a bug.

**Comment by MauritsWilke** [comment]
Thanks for that! If you still want the picture, here it is (sorry for the delay)

https://minecraftpfp.com/api/pfp/DuplexEagle.png

**Comment by MauritsWilke** [comment]
Has this issue persisted?

**Comment by MauritsWilke** [comment]
Assuming it hasn't

**Comment by ghost** [comment]
Hey, sorry I thought I replied. Thanks, your link worked. I also figured out the source of the issue because I had the same problem on other websites. The problem is that LibreWolf (the Firefox based browser that I was referring to in the original post) has a privacy setting enabled by default that blocks websites from using HTML5 Canvas Image Data unless you specifically give permission to the website to use that image data. Once I allowed the website to use that image data, It worked perfectly fine.
