### ISSUE TITLE
My IGN does not work

### ISSUE THREAD

**Issue by DereC4** [MauritsWilke/mcpfp#24]
I can't really isolate this down to a specific set of words or anything, but try using my name as a test case.

derex__

Perhaps it's something to do with the underscores?

**Comment by MauritsWilke** [comment]
https://minecraftpfp.com/generate?ign=derex__

This one works for me, perhaps your account was too new?

**Comment by DereC4** [comment]
I had a good laugh at that because my account has been a thing since 2014, and the username for over 2 years. Maybe it's my adblock or something although other IGNs seem to work.

**Comment by DereC4** [comment]
![image](https://github.com/MauritsWilke/mcpfp/assets/53978637/abd6b96f-0e3b-4b49-8566-85ce122446e3)
Ok what the actual heck I swear it was not working for quite a while but now it is. SOMEHOW
