### ISSUE TITLE
I changed my skin but it hasn’t changed on the website.

### ISSUE THREAD

**Issue by TrainMan207** [MauritsWilke/mcpfp#28]
I changed my in-game skin but the change hasn’t shown up on the website when I put my IGN in. I don’t know if it normally takes a few days or not.

**Comment by Nicolino1706** [comment]
Wait a few hours and the skin on the site will change

**Comment by DWARDL** [comment]
> I changed my in-game skin but the change hasn’t shown up on the website when I put my IGN in. I don’t know if it normally takes a few days or not.

Wait a few hours and the skin on the site will change

**Comment by MauritsWilke** [comment]
Probably fixed
