### ISSUE TITLE
my skin wont load on the website

### ISSUE THREAD

**Issue by zygort** [MauritsWilke/mcpfp#29]
ive put in my ign but when i type it in on the website it just shows steve though it works for my friend
![image_2023-10-14_181411975](https://github.com/MauritsWilke/mcpfp/assets/147940403/eb5595ce-e7af-4e3d-9243-cfc67936a413)

**Comment by GGImortalyty** [comment]
![Uploading Donx.png…]()

**Comment by MauritsWilke** [comment]
Works now
