### ISSUE TITLE
Display's old skin

### ISSUE THREAD

**Issue by Koenfett** [MauritsWilke/mcpfp#3]
The website is displaying my old mc skin than of my new one.

**Comment by MauritsWilke** [comment]
That's likely a caching issue caused by Minotar, i'll look into it to see if I can disable cache. Thanks for bringing it to my attention!

**Comment by Sheepdude289** [comment]
is there a fix for now?

**Comment by MauritsWilke** [comment]
Nope sorry, I cannot change the caching time of Minotaur.
If anyone else found something I missed, feel free to comment it :)
