### ISSUE TITLE
My skin doesn't show on the website (Bodebojo)

### ISSUE THREAD

**Issue by bodebojo** [MauritsWilke/mcpfp#32]
When i go to the website my skin just shoes up as a steve skin.
Java IGN: Bodebojo

**Comment by de-grote** [comment]
wait like 10 mins for it to show up

**Comment by bodebojo** [comment]
Still nothing 
![image](https://github.com/MauritsWilke/mcpfp/assets/92573346/6ad4fd6b-e045-4860-93f2-8452fe6b6d5f)

**Comment by MauritsWilke** [comment]
Works now
