### ISSUE TITLE
Планируется ли добавить поддержки загрузки скина файлом?

### ISSUE THREAD

**Issue by VaveFire** [MauritsWilke/mcpfp#34]
Я являюсь заядлым пиратом и я бы хотел узнать будет ли пожжержка загрузки скина файлом, или поддержки tlauncher, klaunher или на крайняк tllegacy?

**Comment by MauritsWilke** [comment]
> I am an avid pirate and I would like to know if there will be a delay in loading the skin file, or support tlauncher, klaunher or at least tllegacy? (Translated using DeepL)

Support for illegal launchers won't be added, but V2 will allow for custom skin file uploads so that would fix your problem.
> Поддержка нелегальных пусковых установок не будет добавлена, но V2 позволит загружать файлы пользовательских скинов, так что это решит вашу проблему.
