### ISSUE TITLE
My Account is not Working

### ISSUE THREAD

**Issue by ghost** [MauritsWilke/mcpfp#35]
I tried to type in my Minecraft username, which is TheDuckbloxR (Java) and MePeepsYT (Bedrock), but I does not work. Please fix this.

**Comment by uwuv3** [comment]
Skin files are taken by https://minotar.net/, there is nothing that can be done for Bedrock, but it may take time to update java skins

**Comment by MauritsWilke** [comment]
As @uwuv3 said, I don't handle the skin file requests.
I'm sorry, but I can't fix this.
