### ISSUE TITLE
aref

### ISSUE THREAD

**Issue by bozayiwarrior** [MauritsWilke/mcpfp#36]
![6600f558c15a25fc](https://github.com/MauritsWilke/mcpfp/assets/157991361/94e2e523-2844-4b48-94f2-1cc4e9ce6701)

**Comment by bozayiwarrior** [comment]
> ![6600f558c15a25fc](https://private-user-images.githubusercontent.com/157991361/300290918-94e2e523-2844-4b48-94f2-1cc4e9ce6701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NzI5NjYsIm5iZiI6MTcwNjQ3MjY2NiwicGF0aCI6Ii8xNTc5OTEzNjEvMzAwMjkwOTE4LTk0ZTJlNTIzLTI4NDQtNGI0OC05NGYyLTFjYzRlOWNlNjcwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQyMDExMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTBlZWJiZDY4ZGJlMWI2ZDEyZmFlNzQ4NjU0NjA4ZmViYmI2YzNmMGVhZjE3NGJmYmI3YTg1ODRmNTg2YTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T2qfcQQa2wdll3mDwtu_xOGKBcIwZlwsKtVwUQ8y6pU)

**Comment by MauritsWilke** [comment]
Meaning?

**Comment by bozayiwarrior** [comment]
![6600f558c15a25fc](https://github.com/MauritsWilke/mcpfp/assets/157991361/be09d18d-c817-4375-bace-060d1754bc63)

**Comment by MauritsWilke** [comment]
I'm sorry but what are you trying to convey?
