### ISSUE TITLE
My skin is not displayed

### ISSUE THREAD

**Issue by lvmdx** [MauritsWilke/mcpfp#39]
I have a license, I updated my skin a month ago in the official launcher. By going to the site and entering your nickname, nothing changes
![image](https://github.com/MauritsWilke/mcpfp/assets/159695585/adee2652-36d2-4617-a56b-611a1cd1322f)

**Comment by uwuv3** [comment]
Skin files are retrieved by https://minotar.net/, it may take time to update java skins;
Skin file has been updated, topic can be closed.
![image](https://github.com/MauritsWilke/mcpfp/assets/100004271/6b80e40f-6e9c-4faa-9edc-e50ecf95d7f1)

**Comment by QNquenan** [comment]
I have a license too， By going to the site entering my nickname, nothing changes，my nickname is quenana
![QQ_1722342439881](https://github.com/user-attachments/assets/a0ab06f1-eae4-4fe9-aa1b-e668cae2d7ba)
![QQ_1722342481710](https://github.com/user-attachments/assets/ca72da68-a72f-452d-9fbc-62f135ae2198)

**Comment by uwuv3** [comment]
> I have a license too， By going to the site entering my nickname, nothing changes，my nickname is quenana ![QQ_1722342439881](https://private-user-images.githubusercontent.com/113289519/353456210-a0ab06f1-eae4-4fe9-aa1b-e668cae2d7ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTc4NjksIm5iZiI6MTcyMjQxNzU2OSwicGF0aCI6Ii8xMTMyODk1MTkvMzUzNDU2MjEwLWEwYWIwNmYxLWVhZTQtNGZlOS1hYTFiLWU2NjhjYWUyZDdiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwOTE5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGE2Y2JjODg1YjcwYjMxODJiODAxZTNjODFlZmUzNTFjZmUwMjllOTQ4NjhhMjFjODA1YzkwMDdjYWIwYjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JbWki5J5Cl_IdVbz0XSgnKiQTNw593cd-eHD4aQRfsQ) ![QQ_1722342481710](https://private-user-images.githubusercontent.com/113289519/353456355-ca72da68-a72f-452d-9fbc-62f135ae2198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTc4NjksIm5iZiI6MTcyMjQxNzU2OSwicGF0aCI6Ii8xMTMyODk1MTkvMzUzNDU2MzU1LWNhNzJkYTY4LWE3MmYtNDUyZC05ZmJjLTYyZjEzNWFlMjE5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwOTE5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTJiNTU4MzFkMGM3OWQxMWI4NzNiZjIxYmU5N2NmMjk3MzIwOWUyMjViZjgyZTNkZWZmMjk4NWEyMTA1MGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hIItxsFHF7p6f9C99cXWnw2a-aS9s3tR5zYaTR5vPZo)

recheck again

**Comment by MauritsWilke** [comment]
Seems like this has been resolved.
For future reference: this is likely a caching issue that I cannot fix.
