### ISSUE TITLE
Not an issue, but rather a feature, skin.png to pfp

### ISSUE THREAD

**Issue by T3M1N4L** [MauritsWilke/mcpfp#42]
Please create a feautre to have png files of skins to be turned into the pfp rather than just the username

**Comment by BioLocator** [comment]
that would be so useful

**Comment by foxeddev** [comment]
> Please create a feautre to have png files of skins to be turned into the pfp rather than just the username

Quick fix: Change your Minecraft skin, create the avatar, change it back

**Comment by T3M1N4L** [comment]
What if you don't have a Minecraft account?

**Comment by foxeddev** [comment]
Sorry it really would be a nice feature

**Comment by MauritsWilke** [comment]
I know, but I don't have the time to work on this project right now sorry.

**Comment by T3M1N4L** [comment]
This is a feature that should have been added for the beginning since there are many people who play even though they don't have an account
