### ISSUE TITLE
bro my skin aint skining 💀 

### ISSUE THREAD

**Issue by BlazingTNT1** [MauritsWilke/mcpfp#43]
![mcpfp - BlazingTNT2 (1)](https://github.com/user-attachments/assets/f1f60162-64e5-40e6-985e-3caa9bd1ae14)

**Comment by BlazingTNT1** [comment]
fix it i have one eye im not dajaal i have 2 eyes 💀 
![image](https://github.com/user-attachments/assets/ffd3e63b-48e0-4b04-9122-7b7d9910edac)

**Comment by MauritsWilke** [comment]
I recommend you fix this in a photo editing tool as the algorithm cannot account for this.
Both paint.net (windows) and gimp (any platform) are free, you could use those to edit it manually!
