### ISSUE TITLE
Generator wont update

### ISSUE THREAD

**Issue by Mastercrafter83** [MauritsWilke/mcpfp#48]
when i first typed in my name i found out i was wearing the wrong skin, so i switched to the one i wanted to use, but it wont update, the skin shows as updated to servers and minecraft.net but it still shows the original one i used, even on private/incognito mode.

**Comment by MauritsWilke** [comment]
This has to do with the caching of the API I use. You'll just have to wait, sorry.

**Comment by Mastercrafter83** [comment]
wow quick response W

**Comment by Mastercrafter83** [comment]
> This has to do with the caching of the API I use. You'll just have to wait, sorry.

wait btw how long does it last

**Comment by MauritsWilke** [comment]
I think about 48h, but I can't say for certain.
