### ISSUE TITLE
No Skin Changing!

### ISSUE THREAD

**Issue by ghost** [MauritsWilke/mcpfp#8]
Stays as ? skin and doesnot change when the name is edited,
![mcpfp - Golden_Knight_](https://user-images.githubusercontent.com/104498340/192626959-9f99f0cc-bdb8-4c6d-aa00-fd18bc62df9f.png)

**Comment by ghost** [comment]
Took A While To Update Skin Data.

**Comment by MauritsWilke** [comment]
Perhaps your internet, or minotaur (the skin providing service) is struggling. 
Sorry for the late response.
